# Generated by Django 5.1.1 on 2024-12-23 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritodecompras', '0002_auto'),
        ('productos', '0002_producto_precio_docena_producto_precio_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineacarrito',
            name='precio_unidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lineacarrito',
            name='variedad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.variedadempanada'),
        ),
        migrations.AlterField(
            model_name='lineacarrito',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='carritodecompras.carrito'),
        ),
        migrations.AlterField(
            model_name='lineacarrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
