# Generated by Django 5.1.1 on 2024-09-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carritodecompras', '0002_carrito_fecha_creacion_alter_carrito_usuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarritoItem',
        ),
    ]
