# Generated by Django 5.1.1 on 2024-12-23 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritodecompras', '0004_alter_lineacarrito_variedad'),
        ('productos', '0002_producto_precio_docena_producto_precio_unidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineacarrito',
            name='variedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.variedadempanada'),
        ),
    ]
