# Generated by Django 5.1.1 on 2024-10-25 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritodecompras', '0004_carritoitem'),
        ('productos', '0007_alter_producto_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='carrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carritodecompras.carrito'),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='lineacarrito',
            name='carrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carritodecompras.carrito'),
        ),
        migrations.AlterField(
            model_name='lineacarrito',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto'),
        ),
    ]
