# Generated by Django 5.1.1 on 2024-12-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritodecompras', '0006_alter_carrito_usuario_alter_lineacarrito_variedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineacarrito',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
