# Generated by Django 5.1.1 on 2024-11-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_direccion_entrega_pedido_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='direccion_entrega',
            field=models.CharField(default='Direccion no especificada', max_length=250),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.CharField(default='Direccion no especificada', max_length=250),
        ),
    ]
