# Generated by Django 5.1.1 on 2024-11-26 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_detallepedido_direccion_entrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='direccion_entrega',
        ),
    ]
