# Generated by Django 5.1.1 on 2024-11-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_remove_detallepedido_direccion_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
