# Generated by Django 5.1.1 on 2024-12-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_groups_alter_usuario_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Número de teléfono'),
        ),
    ]
