# Generated by Django 5.1.1 on 2024-12-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_precio_docena_producto_precio_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_empanada',
            field=models.BooleanField(default=False),
        ),
    ]
