# Generated by Django 5.1.1 on 2024-12-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_es_empanada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variedadempanada',
            name='precio_unidad',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_media_docena',
            field=models.DecimalField(decimal_places=2, default=8000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_docena',
            field=models.DecimalField(decimal_places=2, default=14000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_unidad',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
        ),
    ]
