# Generated by Django 5.1.1 on 2024-12-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_remove_producto_precio_alter_producto_precio_docena_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_unidad',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='es_empanada',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_docena',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_media_docena',
        ),
    ]
