# Generated by Django 5.1.1 on 2024-12-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carritodecompras', '0009_remove_lineacarrito_precio_unidad_and_more'),
        ('productos', '0007_rename_precio_unidad_producto_precio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariedadEmpanada',
        ),
    ]
